controller_list:
  - name: fake_ur3_arm_controller
    type: $(arg execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_ur3_end_controller
    type: $(arg execution_type)
    joints:
      - wrist_3_joint
initial:  # Define initial robot poses.
  - group: ur3_arm
    pose: home